swagger: '2.0'
info:
  version: 0.0.2
  title: "Digi-API"
paths:
  /newspapers/:
    get:
      description: |
        Returns list of available newspaper titles
      responses:
        '200':
          description: Successful response
  /newspapers/year/:
    get:
      description: |
        Returns list of available journal titles for given year
      responses:
        '200':
          description: Successful response

  /newspapers/decade/:
    get:
      description: |
        Returns list of available journal titles for given year
      responses:
        '200':
          description: Successful response


  /newspapers/year/month/:
    get:
      description: |
        Returns list of available journal titles for given year and month
      responses:
        '200':
          description: Successful response

  /journals/:
    get:
      description: |
        Returns list of available journal titles
      responses:
        '200':
          description: Successful response
